# Generated by Django 4.2.5 on 2023-09-09 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_product_image_alter_review_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='isRecieved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='recievedAt',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
