# Generated by Django 4.2.5 on 2023-09-20 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_product_backorderavailabilitydate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='backorderAvailabilityDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='preorderAvailabilityDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
