# Generated by Django 4.2.5 on 2023-09-22 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_product_backorderavailabilitydate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='isPreorderAvailable',
        ),
        migrations.RemoveField(
            model_name='product',
            name='preorderAvailabilityDate',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='is_backorder',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='is_preorder',
            field=models.BooleanField(default=False),
        ),
    ]
