# Generated by Django 4.2.5 on 2023-09-27 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_remove_customorder_product_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customorder',
            name='custom_product_name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='custom_order',
        ),
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='custom_order',
        ),
        migrations.AddField(
            model_name='customorder',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.product'),
        ),
    ]
