# Generated by Django 4.2.5 on 2023-09-27 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_remove_customorder_custom_product_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='isCustom',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='CustomOrder',
        ),
    ]
