# Generated by Django 4.2.5 on 2023-10-02 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_order_iscustom_delete_customorder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='isCustom',
        ),
    ]
